plugins {
    id 'com.android.application'
}

android {
    namespace 'site.r777b.jukebox'
    compileSdk 35

    defaultConfig {
        applicationId 'site.r777b.jukebox.admin'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.5.0-admin'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
